### ISSUE TITLE
A way to have the module recogize the condition in an effect with another name ?

### ISSUE THREAD

**Issue by LeGrandCinerio** [thatlonelybugbear/automated-conditions-5e#15]
Hello. I was wondering if it was possible to have the module recognize a condition in an effect with another name. In my exemple i am trying to have the "Poisoned" effect being recognize in an effect with the "Rotting Flesh, Bubbons and coughing Flys" (given by the Bulezau monster) name. It is just so my player know where does the effect come from and what are the RP effect of the poisoned condition on their character.

**Comment by thatlonelybugbear** [comment]
This module will be reworked over the next couple of weeks.

I will make a note to provide a way to do what you ask and ping you when it's done ;)

**Comment by thatlonelybugbear** [comment]
@LeGrandCinerio How do you create this custom effects?
Directly on the Character Sheet or Item Sheet effects tab, or through a module like DFreds Convenient Effects?

**Comment by LeGrandCinerio** [comment]
With the Item Sheet. Just having an effect apply to a target when it is hit/fail a saving throw.

**Comment by thatlonelybugbear** [comment]
@LeGrandCinerio are you on dnd5e v3.0.x or 2.4.x?

**Comment by LeGrandCinerio** [comment]
For the moment i am on 2.4 but when MIDI QOL will be update, i will go to 3.0.

**Comment by thatlonelybugbear** [comment]
As you are using MidiQOL, I would suggest checking out DFreds Convenient Effects that works well together.

It has all the dnd5e conditions predefined using MidiQOL flags to give the rolls the proper dis/advantage etc as needed. 
You can duplicate the Poisoned condition and rename it to what you want.

Automated Conditions is meant more to be used for users that do not use any Roller modules (like MidiQOL, WIRE, Ready Set Rolls) as these modules will probably have some integrated (more or less) ways to deal with the rolls.


Having said that, I will make it so that Automated Conditions will be able to pick up `ActiveEffect5e#statuses` instead of just matching by name, and add a compendium Item that will have the basic 5e conditions predefined as needed. Dragging one of these conditions and dropping them on an Item, will create a copy that will have the proper `statuses` defined and changing the name won't matter.

**Comment by thatlonelybugbear** [comment]
@LeGrandCinerio 
So next version of AC5e for v3 dnd5e will offer a way to do exactly that.

Actually 2 ways.
- By adding a flag on the AE similar to `flags.automated-conditions-5e.poisoned | Override | true`
- By adding the core system effect on an Item and renaming as you please. This needs the following to work (which might be helpful to do anyways for the new system version).

  - Create a placeholder Item on the sidebar
  - Enable all conditions on an Actor on the **new** Dnd5e sheet.
  - Change the Actor's character sheet to the **legacy** version.
  - Drag each created condition from the legacy character sheet on the placeholder Item's effects tab.
  - Drag and drop what's needed on the Item you want to create.
  
  
![image](https://github.com/thatlonelybugbear/automated-conditions-5e/assets/7237090/4e9a4d48-86de-4ae6-b74d-a2b03e433d32)
![image](https://github.com/thatlonelybugbear/automated-conditions-5e/assets/7237090/ac8160c0-a664-4eaf-aee4-7d39f6614833)
![image](https://github.com/thatlonelybugbear/automated-conditions-5e/assets/7237090/b004975f-2fbd-499f-a3f9-4ba2ef6d44e6)

**Comment by thatlonelybugbear** [comment]
I will close this, as AC5e don't need conditions by name anymore in v3 dnd5e.

I am reworking the module quite a bit for v12. If anything more is still needed, let me know.
